= JVM debugging
include::_attributes.adoc[]


== Java Thread Dump


A *Java thread dump* is a snapshot of what every thread in the JVM is doing at a particular point in time. Each thread in the JVM is listed with its name and ID, its current state and the Java call stack showing what monitor it has locked or is waiting on.



.Get a Thread Dump
[.console-input]
[source, bash]
----
curl -s -k -u admin:password $RHDG_URL/rest/v2/server/threads
----



== Java Heap Dump

A *Java Heap Dump* is a snapshot of all the objects that are in memory in the JVM at a certain moment. They are very useful for troubleshooting memory leak problems and optimizing memory usage in Java applications. Heap dumps are usually stored in binary format `hprof` files.


.Get a Heap Dump
[.console-input]
[source, bash]
----
# Change "cache-replicated-01" to your desired cache name
curl -X POST -s -k -u admin:password $RHDG_URL/rest/v2/server/memory?action=heap-dump
# Take the filename from the output to copy it to your machine
oc cp cluster-0:/opt/infinispan/server/data/$DUMP_FILENAME.prof . heapdump-cluster-0.hprof
----



== Logging GC messages

The Data Grid Operator does not log Garbage Collector (GC) messages by default. You can direct GC messages to stdout with the following JVM options:


.Configure GC messages to stdout
[.console-input]
[source, yaml]
----
apiVersion: infinispan.org/v1
kind: Infinispan
metadata:
  name: cluster
spec:
  container:
    # If you want to keep the timezone config, just append the following to the existing config
    extraJvmOpts: "-Xlog:gc*:stdout:time,level,tags"
----

If instead, you want the logs in a separate file (as it might be quite verbose), you can use a configuration like the following:

.Configure GC messages to file
[.console-input]
[source, yaml]
----
apiVersion: infinispan.org/v1
kind: Infinispan
metadata:
  name: cluster
spec:
  container:
    # If you want to keep the timezone config, just append the following to the existing config
    extraJvmOpts: "-Xlog:gc*=info:file=/tmp/gc.log:time,level,tags,uptimemillis:filecount=10,filesize=1m"
----



== Analyzing File descriptions

A file descriptor is a number that uniquely identifies an open file in a computer's operating system. It describes a data resource, and how that resource may be accessed. It is needed to open *files*, *network sockets*, etc. There is a *default limit* to the number of opened file descriptors. If you suspect that you are matching that limit, you can check with the following command:

.Get the opened file descriptors
[.console-input]
[source, bash]
----
oc exec cluster-0 -- lsof -P > lsof-cluster-0.txt
----





== JDK Flight Recorder (JFR)

JFR provides *insights into various aspects of JVM performance* to ease cluster inspection and debugging. Depending on your requirements, you can store and analyze your recordings using the integrated tools provided by Cryostat or export the recordings to an external monitoring application.

*Cryostat* is a container-native Java application based on JDK Flight Recorder (JFR) that you can use to monitor Java Virtual Machine (JVM) performance for containerized workloads that run on a Red Hat OpenShift cluster.


The installation of the Cryostat and its dependency, the `cert-manager` operator is out of the scope of this workshop. Therefore, although it is part of the debugging options, we are not presenting detailed steps on how to generate a JFR using Cryostat.



Check the https://access.redhat.com/documentation/en-us/red_hat_data_grid/8.4/html/data_grid_operator_guide/monitoring-services#deploying-cryostat_monitor[JFR section in the Data Grid documentation] and the https://access.redhat.com/documentation/en-us/red_hat_build_of_cryostat/2/html-single/getting_started_with_cryostat/index#installing-cryostat-on-openshift-using-an-operator_cryostat[Getting started section of Cryostat] to get more information on how to install and configure it.

TIP: If you want a simple guide on how to deploy the infrastructure for JFR and a walkthrough on Cryostat, check the https://github.com/alvarolop/rhdg8-server#7-java-flight-recorder[following GH repository].



== Useful KCS

Do you have other needs and you would like to have the `jcmd` command inside the pod? Try the documentation of this KCS:

* KCS: https://access.redhat.com/solutions/6964022[Alternatives for creating heap dump and thread dump in a DG 8 even without the JDK].
* KCS: https://access.redhat.com/solutions/6968671[Troubleshoot options for Data Grid pod crash].
* KCS: https://access.redhat.com/solutions/6962483[Using inspect for DG 8 troubleshooting].
* KCS: https://access.redhat.com/solutions/6452611[DG 8 Troubleshooting steps for issues in OCP 4].
