= Troubleshooting
include::_attributes.adoc[]

As we move forward to our final phase, we enter the Troubleshooting Section. Here, we provide you with essential tools and techniques to tackle any issues that come your way. As an administrator of the infrastructure, you'll master the art of collecting cluster information for effective debugging. Join us in this enlightening section to strengthen your troubleshooting skills and enhance your cache optimization abilities.

Let's start by collecting important details about the Openshift setup, including CRDs and pod logs and events. Then, we'll dig into examining the Data Grid server, getting the caches' configuration and a complete server report. Lastly, we'll focus on JVM debugging, getting info from the Java Heap Dump and Java Thread Dump.


== Openshift information

=== Retrieving the list of server pods

This might seem trivial, but we need to list the pods to then execute other commands inside the pods. Execute the following command to retrieve the full list of pods:

.Example
[.lines_space]
[.console-input]
[source,bash, subs="+macros,+attributes"]
----
oc get pods -n {user}-rhdg
----

.Output of the previous command
[.console-output]
[source,bash, subs="+macros,+attributes"]
----
oc login -u {user} -p openshift {cluster_api}
----



=== Retrieving the Openshift configuration


* oc adm inspect namespace/<rhdg-namespace>
* Or do it manually.





== Server debugging and maintaining


=== Retrieving the Data Grid server report

https://github.com/alvarolop/rhdg8-server#retrieve-server-reports-from-openshift


=== Problems with cache configurations?

https://github.com/alvarolop/rhdg8-server#annex-convert-cache-configurations



== Other useful REST API operations


* Problems with Protobuf? You can list all the `.proto` files using the REST API.
* Problems with cache definitions? Retrieve the list of caches, its configuration and its status (Healthy or not).
* Problems with Server tasks? List them using REST.
* Problems with the content of a cache? Empty the cache using REST.
* Problems with indexes? Reindex a cache.


== When should add here a section about cross-site replication





== JVM debugging


=== Problems with the JVM memory on cluster pods?


* Java Thread Dump
* Java Heap Dump


=== Reached file limit descriptors on a pod?

